import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

/**
 * Launch redirect map: every URL the current WordPress site serves that moves,
 * pointing at its final destination on the new site. Old path on the left, new
 * path on the right, both with the trailing slash `trailingSlash: 'always'`
 * pins, so nothing lands on a second hop.
 *
 * Only URLs that actually change are listed. `/about-us/`, `/contact-us/`,
 * `/career/`, `/testimonials/`, `/book-a-call/`, `/support/` and the three
 * policy pages deliberately keep the paths they already rank on, so they need
 * no entry here.
 *
 * This file is plain JavaScript with no `// @ts-check`, unlike
 * `astro.config.mjs`: typing the two `node:` imports it needs would mean adding
 * `@types/node`, and a redirect table is not worth a new dependency.
 */
export const REDIRECTS = {
  /* The nine service pages now live under /services/. */
  '/shopify-app-development/': '/services/shopify-app-development/',
  '/shopify-growth-marketing/': '/services/shopify-app-marketing/',
  '/shopify-theme-storefront-development/':
    '/services/shopify-theme-storefront-development/',
  '/wordpress-design-development/': '/services/wordpress-design-development/',
  '/wordpress-plugin-development/': '/services/wordpress-plugin-development/',
  '/wordpress-growth-marketing/': '/services/wordpress-growth-marketing/',
  '/website-maintenance/': '/services/website-maintenance/',
  '/seo/': '/services/seo/',

  /**
   * Redirects the current site already serves, carried over so they keep
   * working — they live in WordPress and disappear with it.
   *
   * `/growth-plan/` currently 301s to `/wordpress-growth-marketing/`; it points
   * straight at the final URL here rather than chaining through the old one.
   */
  '/contact/': '/contact-us/',
  '/growth-plan/': '/services/wordpress-growth-marketing/',

  /**
   * Linked from the current footer but has no page behind it — today it 301s to
   * the homepage, so nothing is indexed at this path. /services/ is the nearest
   * real answer to a pricing enquiry; drop this line to let it 404 instead.
   */
  '/pricing/': '/services/',
};

/**
 * Emits the redirect map in the formats static hosts read, so the same table
 * produces a true 301 wherever the site lands.
 *
 * Astro's own `redirects` option is deliberately not used: in a static build it
 * writes an HTML page with a meta refresh at each old path, and on Netlify a
 * file that exists shadows the `_redirects` rule for the same path — the weaker
 * client-side redirect would win over the 301. Emitting only host rules keeps
 * the real 301.
 *
 * - `_redirects` — Netlify and Cloudflare Pages.
 * - `.htaccess` — Apache, which is what the WordPress site runs on today.
 *
 * On any other host (nginx, Vercel, S3/CloudFront) these files are inert:
 * translate the same table into that host's own redirect config. The README
 * carries the map in full.
 */
export function emitHostRedirects() {
  const entries = Object.entries(REDIRECTS);

  return {
    name: 'blinto:host-redirects',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const out = (name) => fileURLToPath(new URL(name, dir));

        const netlify = entries
          .map(([from, to]) => `${from}  ${to}  301`)
          .join('\n');
        await writeFile(out('_redirects'), `${netlify}\n`, 'utf8');

        const apache = [
          '# Generated by redirects.mjs — edit the map there, not here.',
          '<IfModule mod_rewrite.c>',
          '  RewriteEngine On',
          ...entries.map(
            ([from, to]) => `  RewriteRule ^${from.slice(1)}$ ${to} [R=301,L]`,
          ),
          '</IfModule>',
        ].join('\n');
        await writeFile(out('.htaccess'), `${apache}\n`, 'utf8');

        logger.info(
          `wrote ${entries.length} redirects to _redirects and .htaccess`,
        );
      },
    },
  };
}
