import type { LegalBlock } from '../types';

/**
 * Privacy Policy — migrated verbatim from https://blinto.co/privacy-policy/.
 *
 * Legal copy is reproduced word for word: nothing is rewritten, shortened or
 * modernised. Only two things changed. The source heading levels were
 * inconsistent (Elementor emitted h1 for every section here and h6 for
 * subsections elsewhere), so they are normalised into a real document outline;
 * and the contact address, which Cloudflare served obfuscated, is written out.
 */

export const meta = {
  title: 'Privacy Policy — Blinto',
  description:
    'How Blinto LLC collects, uses, retains and discloses your personal data when you use our website and services, and the rights you have over it.',
};

export const hero = {
  eyebrow: 'Legal',
  heading: 'Privacy Policy',
};

export const blocks: LegalBlock[] = [
  { kind: 'text', text: 'This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.' },
  { kind: 'text', text: 'We use Your data to provide and improve the Service. By using the Service, You agree to this Privacy Policy’s collection and use of information.' },
  { kind: 'heading', level: 2, text: 'Interpretation and Definitions' },
  { kind: 'heading', level: 3, text: 'Interpretation' },
  { kind: 'text', text: 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.' },
  { kind: 'heading', level: 3, text: 'Definitions' },
  { kind: 'text', text: 'For this Privacy Policy:' },
  {
    kind: 'list',
    items: [
      'Account means a unique account created for You to access our Service or parts of our Service.',
      'Affiliate means an entity that controls is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.',
      'Company (referred to as either “the Company,” “We,” “Us,” or “Our” in this Cookies Policy) refers to Blinto LLC, 30 N Gould St Ste R Sheridan, WY 82801, USA.',
    ],
  },
  { kind: 'text', text: 'Cookies are small files placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.' },
  {
    kind: 'list',
    items: [
      'Country refers to: Wyoming, United States.',
    ],
  },
  { kind: 'text', text: 'Device means any device that can access the Service, such as a computer, a cell phone, or a digital tablet.' },
  { kind: 'text', text: 'Personal Data is any information that relates to an identified or identifiable individual.' },
  { kind: 'text', text: 'Service refers to the Website.' },
  {
    kind: 'list',
    items: [
      'A service provider is any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.',
    ],
  },
  { kind: 'text', text: 'Third-party Social Media Service refers to any website or social network website through which a User can log in or create an account to use the Service.' },
  {
    kind: 'list',
    items: [
      'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
    ],
  },
  { kind: 'text', text: 'The website refers to Blinto, accessible from blinto.co' },
  {
    kind: 'list',
    items: [
      'You mean the individual accessing or using the Service, the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
    ],
  },
  { kind: 'heading', level: 2, text: 'Collecting and Using Your Personal Data' },
  { kind: 'heading', level: 3, text: 'Types of Data Collected' },
  { kind: 'text', text: 'Personal Data' },
  { kind: 'text', text: 'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:' },
  {
    kind: 'list',
    items: [
      'Email address',
      'First name and last name',
      'Phone number',
      'Address, State, Province,',
    ],
  },
  { kind: 'text', text: 'ZIP/Postal code, City' },
  { kind: 'text', text: 'Usage Data' },
  { kind: 'text', text: 'Usage Data is collected automatically when using the Service.' },
  { kind: 'text', text: 'Usage Data may include information such as Your Device’s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.' },
  { kind: 'text', text: 'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device’s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.' },
  { kind: 'text', text: 'Information from Third-Party Social Media Services' },
  { kind: 'text', text: 'The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:' },
  {
    kind: 'list',
    items: [
      'Google',
      'Facebook',
      'Instagram',
      'Twitter',
      'LinkedIn',
    ],
  },
  { kind: 'text', text: 'Suppose You decide to register through or otherwise grant us access to a Third-Party Social Media Service. In that case, We may collect Personal data already associated with Your Third-Party Social Media Service account, such as Your name, email address, activities, or contact list associated with that account.' },
  { kind: 'text', text: 'You may also share additional information with the Company through Your Third-Party Social Media Service’s account.' },
  { kind: 'text', text: 'Suppose you provide such information and Personal Data, during registration or otherwise. In that case, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.' },
  { kind: 'text', text: 'Tracking Technologies and Cookies' },
  { kind: 'text', text: 'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies are beacons, tags, and scripts to collect and track information and improve and analyze Our Service. The technologies We use may include:' },
  {
    kind: 'list',
    items: [
      'Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a cookie is being sent. However, if You do not accept Cookies, You may be unable to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse cookies, our Service may use Cookies.',
      'Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a specific section and verifying system and server integrity).',
    ],
  },
  { kind: 'text', text: 'Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on this website article.' },
  { kind: 'text', text: 'We use both Session and Persistent Cookies for the purposes set out below:' },
  { kind: 'heading', level: 4, text: 'Necessary / Essential Cookies' },
  { kind: 'text', text: 'Type: Session Cookies' },
  { kind: 'text', text: 'Administered by: Us' },
  { kind: 'text', text: 'Purpose: These cookies are essential to provide you with services available through the website and enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.' },
  { kind: 'text', text: 'Cookies Policy / Notice Acceptance Cookies' },
  { kind: 'text', text: 'Type: Persistent Cookies' },
  { kind: 'text', text: 'Administered by: Us' },
  { kind: 'text', text: 'Purpose: These Cookies identify if users have accepted cookies on the Website.' },
  { kind: 'heading', level: 4, text: 'Functionality Cookies' },
  { kind: 'text', text: 'Type: Persistent Cookies' },
  { kind: 'text', text: 'Administered by: Us' },
  { kind: 'text', text: 'Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid having to re-enter your preferences every time You use the Website.' },
  { kind: 'text', text: 'For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.' },
  { kind: 'heading', level: 3, text: 'Use of Your Data' },
  {
    kind: 'list',
    items: [
      'The Company may use Personal Data for the following purposes:',
      'To provide and maintain our Service, including monitoring the usage of our Service.',
      'To manage Your Account: to manage Your registration as a Service user. The Personal Data You provide can give You access to different Service functionalities as a registered user.',
      'For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.',
      'To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.',
      'To provide You with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.',
      'To manage Your requests: To attend and manage Your requests to Us.',
      'For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.',
      'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and your experience.',
      'We may share Your personal information in the following situations:',
      'With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, and to contact You.',
      'For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company',
      'With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or are under common control with Us.',
      'With business partners: We may share Your information with Our business partners to offer You certain products, services, or promotions.',
      'With other users: When you share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside. Suppose You interact with other users or register through a Third-Party Social Media Service. In that case, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures, and activity description. Similarly, other users can view descriptions of Your activity, communicate with You, and view Your profile',
      'With Your consent: We may disclose Your personal information for any other purpose with Your consent.',
    ],
  },
  { kind: 'heading', level: 3, text: 'Retention of Your Personal Data' },
  { kind: 'text', text: 'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.' },
  { kind: 'text', text: 'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.' },
  { kind: 'heading', level: 3, text: 'Transfer of Your Personal Data' },
  { kind: 'text', text: 'Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.' },
  { kind: 'text', text: 'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.' },
  { kind: 'text', text: 'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.' },
  { kind: 'heading', level: 2, text: 'Delete Your Personal Data' },
  { kind: 'text', text: 'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.' },
  { kind: 'text', text: 'Our Service may give You the ability to delete certain information about You from within the Service.' },
  { kind: 'text', text: 'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.' },
  { kind: 'text', text: 'Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.' },
  { kind: 'heading', level: 3, text: 'Disclosure of Your Personal Data' },
  { kind: 'text', text: 'Business Transactions' },
  { kind: 'text', text: 'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.' },
  { kind: 'heading', level: 2, text: 'Law enforcement' },
  { kind: 'text', text: 'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).' },
  { kind: 'heading', level: 3, text: 'Other legal requirements' },
  { kind: 'text', text: 'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:' },
  {
    kind: 'list',
    items: [
      'Comply with a legal obligation',
      'Protect and defend the rights or property of the Company',
      'Prevent or investigate possible wrongdoing in connection with the Service',
      'Protect the personal safety of Users of the Service or the public',
      'Protect against legal liability',
    ],
  },
  { kind: 'heading', level: 3, text: 'Security of Your Personal Data' },
  { kind: 'text', text: 'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.' },
  { kind: 'heading', level: 2, text: 'Children’s Privacy' },
  { kind: 'text', text: 'Our Service only addresses people under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13. If You are a parent or guardian and Know that Your child has provided Us with Personal Data, please contact Us. Suppose We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent. In that case, we remove that information from Our servers.' },
  { kind: 'text', text: 'If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.' },
  { kind: 'heading', level: 2, text: 'Links to Other Websites' },
  { kind: 'text', text: 'Our Service may contain links to other websites not operated by Us. If You click on a third-party link, You will be directed to that third-party’s site. We strongly advise You to review the Privacy Policy of every site You visit.' },
  { kind: 'text', text: 'We have no control over and assume no responsibility for any third-party sites or services’ content, privacy policies, or practices.' },
  { kind: 'heading', level: 2, text: 'Changes to this Privacy Policy' },
  { kind: 'text', text: 'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.' },
  { kind: 'text', text: 'We will inform You via email and/or a prominent notice on Our Service, before the change becomes effective and update the “Last updated” date at the top of this Privacy Policy.' },
  { kind: 'text', text: 'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when posted on this page.' },
  { kind: 'heading', level: 2, text: 'Contact Us' },
  { kind: 'text', text: 'If you have any questions about this Privacy Policy, You can contact us:' },
  { kind: 'text', text: 'By email: info@blinto.co' },
  { kind: 'text', text: 'By visiting this page on our website: https://blinto.co/contact-us/' },
  { kind: 'text', text: 'By phone number: (818) 474-8731' },
];
